language: python
install:
- pip install -r requirements.txt
script:
- mkdocs build --verbose --clean
deploy:
 provider: pages
 keep-history: true
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: site
 committer-from-gh: true
 verbose: true
 on:
   branch: master
