site_name: "Pi-hole documentation"
site_url: https://pi-hole.github.io/docs/
copyright: 'Copyright &copy; 2017 Pi-hole LLC'
repo_name: pi-hole/docs
repo_url: https://github.com/pi-hole/docs
edit_uri: ../docs/edit/master/docs/
remote_branch: gh-pages
theme: material
pages:
- 'Information & Support': 'index.md'
- 'Prerequisites': 'prerequesites.md'
- 'Guides':
  - 'Pi-hole and OpenVPN Server':
    - 'Overview': 'guides/vpn/overview.md'
    - 'Installation': 'guides/vpn/installation.md'
    - 'Setup OpenVPN Server': 'guides/vpn/setup-openvpn-server.md'
    - 'Firewall Configuration': 'guides/vpn/firewall.md'
    - 'Connecting clients': 'guides/vpn/clients.md'
    - 'Optional: Only route DNS via VPN': 'guides/vpn/only-dns-via-vpn.md'
    - 'Optional: Dual operation: LAN & VPN at the same time': 'guides/vpn/dual-operation.md'
extra:
  social:
    - type: globe
      link: https://pi-hole.net
    - type: github-alt
      link: https://github.com/pi-hole
