site_name: "Pi-hole documentation"
site_url: https://pi-hole.github.io/docs/
copyright: 'Copyright &copy; 2018 Pi-hole LLC'
remote_branch: gh-pages
theme:
  name: 'material'
  favicon: 'images/favicon.png'
  language: 'en'

markdown_extensions:
  - codehilite(guess_lang=true)
  - toc(permalink=true)
  - admonition
  - pymdownx.magiclink
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - footnotes
pages:
- 'Overview & Support': 'index.md'
- 'Getting Started':
  - 'Prerequisites': 'main/prerequesites.md'
  - 'Installation': 'main/basic-install.md'
  - 'Post-Install': 'main/post-install.md'
  - 'Updating': 'main/update.md'
- 'FTLDNS':
  - 'Overview': "ftldns/index.md"
  - 'RegEx blocking': "ftldns/regex.md"
  - 'In-depth manual': "ftldns/in-depth.md"
- 'Guides':
  - 'Pi-hole and OpenVPN Server':
    - 'Overview': 'guides/vpn/overview.md'
    - 'Installation': 'guides/vpn/installation.md'
    - 'Setup OpenVPN Server': 'guides/vpn/setup-openvpn-server.md'
    - 'Firewall Configuration': 'guides/vpn/firewall.md'
    - 'Connecting clients': 'guides/vpn/clients.md'
    - 'Optional: Only route DNS via VPN': 'guides/vpn/only-dns-via-vpn.md'
    - 'Optional: Dual operation: LAN & VPN at the same time': 'guides/vpn/dual-operation.md'
extra:
  social:
    - type: globe
      link: https://pi-hole.net
    - type: github-alt
      link: https://github.com/pi-hole
extra_css: [extra.css]
